### ISSUE TITLE
Docker Suggest Run Command not working

### ISSUE THREAD

**Issue by althe3rd** [roadiz/docker-image#2]
Please keep in mind that I am new to docker so i imagine there just may be something I am missing but after downloading the zip of the repo, unzipping it, and trying to build the docker image I then get to the docker run step and get stuck with the suggested command in the readme.  

I get an error saying that a run command needs at least 1 argument.  If I remove all of the extra arguments and just run "docker run roadiz/roadiz" it seems to do something but I never get to a working roadiz installation. It basically hangs after "php5-fpm-config entered RUNNING state".

So my overall question/issue is what might be going wrong and once it is working where will it be accessible? the ip address, localhost with a port,  or will a hosts file entry be added as part of the run command?

Thanks for your help I really hope to pick up more of the ins and outs of docker as quickly as possible.

**Comment by ambroisemaupate** [comment]
Hi @althe3rd. I think your `docker run roadiz/roadiz` command works, it’s just you forgot to run it in background and to *bind the port 80* to access to your container from outside. Try 

```
docker run --name=my-roadiz  -d -p 80 roadiz/roadiz
```

Then wait for a moment, Roadiz should download its dependencies. You will find the port using `docker ps`, then go to your browser and type `localhost:your-container-port`. If you are using boot2docker replace localhost by your docker machine IP. Try reloading your page until roadiz container is ready, you should see Roadiz install.

Keep in my mind that with this example, you won’t have any database, so you’ll have to use *sqlite* during Roadiz installation.

**Comment by ambroisemaupate** [comment]
You can also use `docker pull roadiz/roadiz` as the image is available on https://registry.hub.docker.com/u/roadiz/roadiz/

**Comment by althe3rd** [comment]
Thank you so much for your patience and your advice regarding my questions.  I think I am slowly but surely starting to understand docker better.

With your advice in mind I got rid of any previous docker containers and started fresh using "docker pull roadiz/roadiz" to get the image.  And then used the command in your first reply to run it since the ones mentioned in the readme don't seem to work (is that due to differences in new docker versions perhaps?).  After that I was a bit confused on how to find the IP it is running on but then found the docker inspect command to find the IP address.

Once I also grasped how boot2docker worked I was able to access the docker install screen.  I look forward to diving into both docker and roadiz further.

Thank you very much for your help!

**Comment by althe3rd** [comment]
Forgot to mention that I will also be spending considerable time trying to better understand the creation of the multiple containers for the data volume.

Let me know if you would prefer this be a separate github issue or just keep it as a side conversation as it has more to do with docker than roadiz, but I was wondering if you could point me in the right direction when it comes to getting the other container working for the data volume.  I know you are likely busy so don't feel too obligated to answer or go into great detail, just figured I would ask considering your expertise.

I am currently using a few online video walk throughs of docker to learn more but haven't found one that best explains how to setup separate containers for data volumes.
